// Generated by gencpp from file px4_command/ControlParameter.msg
// DO NOT EDIT!


#ifndef PX4_COMMAND_MESSAGE_CONTROLPARAMETER_H
#define PX4_COMMAND_MESSAGE_CONTROLPARAMETER_H

#include <ros/service_traits.h>


#include <px4_command/ControlParameterRequest.h>
#include <px4_command/ControlParameterResponse.h>


namespace px4_command
{

struct ControlParameter
{

typedef ControlParameterRequest Request;
typedef ControlParameterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ControlParameter
} // namespace px4_command


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::px4_command::ControlParameter > {
  static const char* value()
  {
    return "6564e4eb6ec261394b295cdd4e73b53a";
  }

  static const char* value(const ::px4_command::ControlParameter&) { return value(); }
};

template<>
struct DataType< ::px4_command::ControlParameter > {
  static const char* value()
  {
    return "px4_command/ControlParameter";
  }

  static const char* value(const ::px4_command::ControlParameter&) { return value(); }
};


// service_traits::MD5Sum< ::px4_command::ControlParameterRequest> should match
// service_traits::MD5Sum< ::px4_command::ControlParameter >
template<>
struct MD5Sum< ::px4_command::ControlParameterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::px4_command::ControlParameter >::value();
  }
  static const char* value(const ::px4_command::ControlParameterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::px4_command::ControlParameterRequest> should match
// service_traits::DataType< ::px4_command::ControlParameter >
template<>
struct DataType< ::px4_command::ControlParameterRequest>
{
  static const char* value()
  {
    return DataType< ::px4_command::ControlParameter >::value();
  }
  static const char* value(const ::px4_command::ControlParameterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::px4_command::ControlParameterResponse> should match
// service_traits::MD5Sum< ::px4_command::ControlParameter >
template<>
struct MD5Sum< ::px4_command::ControlParameterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::px4_command::ControlParameter >::value();
  }
  static const char* value(const ::px4_command::ControlParameterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::px4_command::ControlParameterResponse> should match
// service_traits::DataType< ::px4_command::ControlParameter >
template<>
struct DataType< ::px4_command::ControlParameterResponse>
{
  static const char* value()
  {
    return DataType< ::px4_command::ControlParameter >::value();
  }
  static const char* value(const ::px4_command::ControlParameterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PX4_COMMAND_MESSAGE_CONTROLPARAMETER_H
