// Generated by gencpp from file px4_command/Emergency.msg
// DO NOT EDIT!


#ifndef PX4_COMMAND_MESSAGE_EMERGENCY_H
#define PX4_COMMAND_MESSAGE_EMERGENCY_H

#include <ros/service_traits.h>


#include <px4_command/EmergencyRequest.h>
#include <px4_command/EmergencyResponse.h>


namespace px4_command
{

struct Emergency
{

typedef EmergencyRequest Request;
typedef EmergencyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Emergency
} // namespace px4_command


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::px4_command::Emergency > {
  static const char* value()
  {
    return "93c434e74035b38e21439a8069e6541a";
  }

  static const char* value(const ::px4_command::Emergency&) { return value(); }
};

template<>
struct DataType< ::px4_command::Emergency > {
  static const char* value()
  {
    return "px4_command/Emergency";
  }

  static const char* value(const ::px4_command::Emergency&) { return value(); }
};


// service_traits::MD5Sum< ::px4_command::EmergencyRequest> should match
// service_traits::MD5Sum< ::px4_command::Emergency >
template<>
struct MD5Sum< ::px4_command::EmergencyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::px4_command::Emergency >::value();
  }
  static const char* value(const ::px4_command::EmergencyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::px4_command::EmergencyRequest> should match
// service_traits::DataType< ::px4_command::Emergency >
template<>
struct DataType< ::px4_command::EmergencyRequest>
{
  static const char* value()
  {
    return DataType< ::px4_command::Emergency >::value();
  }
  static const char* value(const ::px4_command::EmergencyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::px4_command::EmergencyResponse> should match
// service_traits::MD5Sum< ::px4_command::Emergency >
template<>
struct MD5Sum< ::px4_command::EmergencyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::px4_command::Emergency >::value();
  }
  static const char* value(const ::px4_command::EmergencyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::px4_command::EmergencyResponse> should match
// service_traits::DataType< ::px4_command::Emergency >
template<>
struct DataType< ::px4_command::EmergencyResponse>
{
  static const char* value()
  {
    return DataType< ::px4_command::Emergency >::value();
  }
  static const char* value(const ::px4_command::EmergencyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PX4_COMMAND_MESSAGE_EMERGENCY_H
