// Generated by gencpp from file px4_command/GeneralInfo.msg
// DO NOT EDIT!


#ifndef PX4_COMMAND_MESSAGE_GENERALINFO_H
#define PX4_COMMAND_MESSAGE_GENERALINFO_H

#include <ros/service_traits.h>


#include <px4_command/GeneralInfoRequest.h>
#include <px4_command/GeneralInfoResponse.h>


namespace px4_command
{

struct GeneralInfo
{

typedef GeneralInfoRequest Request;
typedef GeneralInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GeneralInfo
} // namespace px4_command


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::px4_command::GeneralInfo > {
  static const char* value()
  {
    return "f5411d5ea2241dbc1c5aa4c2c6403d8d";
  }

  static const char* value(const ::px4_command::GeneralInfo&) { return value(); }
};

template<>
struct DataType< ::px4_command::GeneralInfo > {
  static const char* value()
  {
    return "px4_command/GeneralInfo";
  }

  static const char* value(const ::px4_command::GeneralInfo&) { return value(); }
};


// service_traits::MD5Sum< ::px4_command::GeneralInfoRequest> should match
// service_traits::MD5Sum< ::px4_command::GeneralInfo >
template<>
struct MD5Sum< ::px4_command::GeneralInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::px4_command::GeneralInfo >::value();
  }
  static const char* value(const ::px4_command::GeneralInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::px4_command::GeneralInfoRequest> should match
// service_traits::DataType< ::px4_command::GeneralInfo >
template<>
struct DataType< ::px4_command::GeneralInfoRequest>
{
  static const char* value()
  {
    return DataType< ::px4_command::GeneralInfo >::value();
  }
  static const char* value(const ::px4_command::GeneralInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::px4_command::GeneralInfoResponse> should match
// service_traits::MD5Sum< ::px4_command::GeneralInfo >
template<>
struct MD5Sum< ::px4_command::GeneralInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::px4_command::GeneralInfo >::value();
  }
  static const char* value(const ::px4_command::GeneralInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::px4_command::GeneralInfoResponse> should match
// service_traits::DataType< ::px4_command::GeneralInfo >
template<>
struct DataType< ::px4_command::GeneralInfoResponse>
{
  static const char* value()
  {
    return DataType< ::px4_command::GeneralInfo >::value();
  }
  static const char* value(const ::px4_command::GeneralInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PX4_COMMAND_MESSAGE_GENERALINFO_H
