// Generated by gencpp from file px4_command/MultiPayloadAction.msg
// DO NOT EDIT!


#ifndef PX4_COMMAND_MESSAGE_MULTIPAYLOADACTION_H
#define PX4_COMMAND_MESSAGE_MULTIPAYLOADACTION_H

#include <ros/service_traits.h>


#include <px4_command/MultiPayloadActionRequest.h>
#include <px4_command/MultiPayloadActionResponse.h>


namespace px4_command
{

struct MultiPayloadAction
{

typedef MultiPayloadActionRequest Request;
typedef MultiPayloadActionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MultiPayloadAction
} // namespace px4_command


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::px4_command::MultiPayloadAction > {
  static const char* value()
  {
    return "901dfe89bb4f4622133561aed17b3eb7";
  }

  static const char* value(const ::px4_command::MultiPayloadAction&) { return value(); }
};

template<>
struct DataType< ::px4_command::MultiPayloadAction > {
  static const char* value()
  {
    return "px4_command/MultiPayloadAction";
  }

  static const char* value(const ::px4_command::MultiPayloadAction&) { return value(); }
};


// service_traits::MD5Sum< ::px4_command::MultiPayloadActionRequest> should match
// service_traits::MD5Sum< ::px4_command::MultiPayloadAction >
template<>
struct MD5Sum< ::px4_command::MultiPayloadActionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::px4_command::MultiPayloadAction >::value();
  }
  static const char* value(const ::px4_command::MultiPayloadActionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::px4_command::MultiPayloadActionRequest> should match
// service_traits::DataType< ::px4_command::MultiPayloadAction >
template<>
struct DataType< ::px4_command::MultiPayloadActionRequest>
{
  static const char* value()
  {
    return DataType< ::px4_command::MultiPayloadAction >::value();
  }
  static const char* value(const ::px4_command::MultiPayloadActionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::px4_command::MultiPayloadActionResponse> should match
// service_traits::MD5Sum< ::px4_command::MultiPayloadAction >
template<>
struct MD5Sum< ::px4_command::MultiPayloadActionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::px4_command::MultiPayloadAction >::value();
  }
  static const char* value(const ::px4_command::MultiPayloadActionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::px4_command::MultiPayloadActionResponse> should match
// service_traits::DataType< ::px4_command::MultiPayloadAction >
template<>
struct DataType< ::px4_command::MultiPayloadActionResponse>
{
  static const char* value()
  {
    return DataType< ::px4_command::MultiPayloadAction >::value();
  }
  static const char* value(const ::px4_command::MultiPayloadActionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PX4_COMMAND_MESSAGE_MULTIPAYLOADACTION_H
