(cl:in-package px4_command-srv)
(cl:export '(CONTROLLERNAME-VAL
          CONTROLLERNAME
          DRONEMASS-VAL
          DRONEMASS
          CABLELENGTH-VAL
          CABLELENGTH
          A_J-VAL
          A_J
          PAYLOADMASS-VAL
          PAYLOADMASS
          MOTOR_SLOPE-VAL
          MOTOR_SLOPE
          MOTOR_INTERCEPT-VAL
          MOTOR_INTERCEPT
          NUM_DRONE-VAL
          NUM_DRONE
          ISPUBAUXILIARYSTATE-VAL
          ISPUBAUXILIARYSTATE
          ISADDONFORCEDUSED-VAL
          ISADDONFORCEDUSED
          ISCROSSFEEDINGTERMSUSED-VAL
          ISCROSSFEEDINGTERMSUSED
          T_JX-VAL
          T_JX
          T_JY-VAL
          T_JY
          T_JZ-VAL
          T_JZ
          KV_XY-VAL
          KV_XY
          KV_Z-VAL
          KV_Z
          KR_XY-VAL
          KR_XY
          KR_Z-VAL
          KR_Z
          KL-VAL
          KL
          KPHI_XY-VAL
          KPHI_XY
          KPHI_Z-VAL
          KPHI_Z
          KR1_X-VAL
          KR1_X
          KR1_Y-VAL
          KR1_Y
          KR1_Z-VAL
          KR1_Z
          KR2_X-VAL
          KR2_X
          KR2_Y-VAL
          KR2_Y
          KR2_Z-VAL
          KR2_Z
          KP_X-VAL
          KP_X
          KP_Y-VAL
          KP_Y
          KP_Z-VAL
          KP_Z
          KOMEGA_X-VAL
          KOMEGA_X
          KOMEGA_Y-VAL
          KOMEGA_Y
          KOMEGA_Z-VAL
          KOMEGA_Z
          LAMBDAJ_X-VAL
          LAMBDAJ_X
          LAMBDAJ_Y-VAL
          LAMBDAJ_Y
          LAMBDAJ_Z-VAL
          LAMBDAJ_Z
          LAMBDA_T_X-VAL
          LAMBDA_T_X
          LAMBDA_T_Y-VAL
          LAMBDA_T_Y
          LAMBDA_T_Z-VAL
          LAMBDA_T_Z
          LAMBDA_R_X-VAL
          LAMBDA_R_X
          LAMBDA_R_Y-VAL
          LAMBDA_R_Y
          LAMBDA_R_Z-VAL
          LAMBDA_R_Z
          LAMBDA1_X-VAL
          LAMBDA1_X
          LAMBDA1_Y-VAL
          LAMBDA1_Y
          LAMBDA1_Z-VAL
          LAMBDA1_Z
          LAMBDA2_X-VAL
          LAMBDA2_X
          LAMBDA2_Y-VAL
          LAMBDA2_Y
          LAMBDA2_Z-VAL
          LAMBDA2_Z
          PXY_ERROR_MAX-VAL
          PXY_ERROR_MAX
          PZ_ERROR_MAX-VAL
          PZ_ERROR_MAX
          PXY_INT_MAX-VAL
          PXY_INT_MAX
          PZ_INT_MAX-VAL
          PZ_INT_MAX
          TILT_MAX-VAL
          TILT_MAX
          INT_START_ERROR-VAL
          INT_START_ERROR
          FP_MAX_X-VAL
          FP_MAX_X
          FP_MAX_Y-VAL
          FP_MAX_Y
          FP_MAX_Z-VAL
          FP_MAX_Z
          OKTOSTART-VAL
          OKTOSTART
))