(cl:in-package px4_command-msg)
(cl:export '(HEADER-VAL
          HEADER
          Q_0-VAL
          Q_0
          Q_1-VAL
          Q_1
          Q_2-VAL
          Q_2
          Q_3-VAL
          Q_3
          R_JX-VAL
          R_JX
          R_JY-VAL
          R_JY
          V_JX-VAL
          V_JX
          V_JY-VAL
          V_JY
          L_MEASURED-VAL
          L_MEASURED
          POS_ERROR_X-VAL
          POS_ERROR_X
          POS_ERROR_Y-VAL
          POS_ERROR_Y
          POS_ERROR_Z-VAL
          POS_ERROR_Z
          ANGLE_ERROR_X-VAL
          ANGLE_ERROR_X
          ANGLE_ERROR_Y-VAL
          ANGLE_ERROR_Y
          ANGLE_ERROR_Z-VAL
          ANGLE_ERROR_Z
          EULER_ROLL-VAL
          EULER_ROLL
          EULER_PITCH-VAL
          EULER_PITCH
          EULER_YAW-VAL
          EULER_YAW
          FLJ_X-VAL
          FLJ_X
          FLJ_Y-VAL
          FLJ_Y
          FLJ_Z-VAL
          FLJ_Z
          DELTA_JP_X-VAL
          DELTA_JP_X
          DELTA_JP_Y-VAL
          DELTA_JP_Y
          DELTA_JP_Z-VAL
          DELTA_JP_Z
          ACC_X-VAL
          ACC_X
          ACC_Y-VAL
          ACC_Y
          ACC_Z-VAL
          ACC_Z
          RD_JX-VAL
          RD_JX
          RD_JY-VAL
          RD_JY
))