(cl:in-package px4_command-msg)
(cl:export '(HEADER-VAL
          HEADER
          CONNECTED-VAL
          CONNECTED
          ARMED-VAL
          ARMED
          MODE-VAL
          MODE
          TIME_FROM_START-VAL
          TIME_FROM_START
          LONGITUDE-VAL
          LONGITUDE
          LATITUDE-VAL
          LATITUDE
          POSITION-VAL
          POSITION
          VELOCITY-VAL
          VELOCITY
          ATTITUDE-VAL
          ATTITUDE
          ATTITUDE_Q-VAL
          ATTITUDE_Q
          ATTITUDE_RATE-VAL
          ATTITUDE_RATE
          ACCELERATION-VAL
          ACCELERATION
          PAYLOAD_VEL-VAL
          PAYLOAD_VEL
          PAYLOAD_POS-VAL
          PAYLOAD_POS
          PAYLOAD_QUATERNION-VAL
          PAYLOAD_QUATERNION
          PAYLOAD_ANGULAR_VEL-VAL
          PAYLOAD_ANGULAR_VEL
          BATTERY_VOLTAGE-VAL
          BATTERY_VOLTAGE
          BATTERY_REMAINING-VAL
          BATTERY_REMAINING
          MOCAPOK-VAL
          MOCAPOK
))