(cl:in-package px4_command-msg)
(cl:export '(HEADER-VAL
          HEADER
          W_X-VAL
          W_X
          W_Y-VAL
          W_Y
          W_Z-VAL
          W_Z
          Q_0-VAL
          Q_0
          Q_1-VAL
          Q_1
          Q_2-VAL
          Q_2
          Q_3-VAL
          Q_3
          R_X-VAL
          R_X
          R_Y-VAL
          R_Y
          V_X-VAL
          V_X
          V_Y-VAL
          V_Y
          POS_ERROR_X-VAL
          POS_ERROR_X
          POS_ERROR_Y-VAL
          POS_ERROR_Y
          POS_ERROR_Z-VAL
          POS_ERROR_Z
          VEL_ERROR_X-VAL
          VEL_ERROR_X
          VEL_ERROR_Y-VAL
          VEL_ERROR_Y
          VEL_ERROR_Z-VAL
          VEL_ERROR_Z
          LM_X-VAL
          LM_X
          LM_Y-VAL
          LM_Y
          LM_Z-VAL
          LM_Z
          VPM_X-VAL
          VPM_X
          VPM_Y-VAL
          VPM_Y
          VPM_Z-VAL
          VPM_Z
          FL_X-VAL
          FL_X
          FL_Y-VAL
          FL_Y
          FL_Z-VAL
          FL_Z
          ACC_X-VAL
          ACC_X
          ACC_Y-VAL
          ACC_Y
          ACC_Z-VAL
          ACC_Z
))