// Generated by gencpp from file px4_command/ControlParameterResponse.msg
// DO NOT EDIT!


#ifndef PX4_COMMAND_MESSAGE_CONTROLPARAMETERRESPONSE_H
#define PX4_COMMAND_MESSAGE_CONTROLPARAMETERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_command
{
template <class ContainerAllocator>
struct ControlParameterResponse_
{
  typedef ControlParameterResponse_<ContainerAllocator> Type;

  ControlParameterResponse_()
    : oktostart(false)  {
    }
  ControlParameterResponse_(const ContainerAllocator& _alloc)
    : oktostart(false)  {
  (void)_alloc;
    }



   typedef uint8_t _oktostart_type;
  _oktostart_type oktostart;





  typedef boost::shared_ptr< ::px4_command::ControlParameterResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_command::ControlParameterResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ControlParameterResponse_

typedef ::px4_command::ControlParameterResponse_<std::allocator<void> > ControlParameterResponse;

typedef boost::shared_ptr< ::px4_command::ControlParameterResponse > ControlParameterResponsePtr;
typedef boost::shared_ptr< ::px4_command::ControlParameterResponse const> ControlParameterResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_command::ControlParameterResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_command::ControlParameterResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_command::ControlParameterResponse_<ContainerAllocator1> & lhs, const ::px4_command::ControlParameterResponse_<ContainerAllocator2> & rhs)
{
  return lhs.oktostart == rhs.oktostart;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_command::ControlParameterResponse_<ContainerAllocator1> & lhs, const ::px4_command::ControlParameterResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_command

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_command::ControlParameterResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_command::ControlParameterResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_command::ControlParameterResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_command::ControlParameterResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_command::ControlParameterResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_command::ControlParameterResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_command::ControlParameterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "860a691c70e14a4dcb7ec7957ddafcce";
  }

  static const char* value(const ::px4_command::ControlParameterResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x860a691c70e14a4dULL;
  static const uint64_t static_value2 = 0xcb7ec7957ddafcceULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_command::ControlParameterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_command/ControlParameterResponse";
  }

  static const char* value(const ::px4_command::ControlParameterResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_command::ControlParameterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool oktostart\n"
;
  }

  static const char* value(const ::px4_command::ControlParameterResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_command::ControlParameterResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.oktostart);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlParameterResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_command::ControlParameterResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_command::ControlParameterResponse_<ContainerAllocator>& v)
  {
    s << indent << "oktostart: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.oktostart);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_COMMAND_MESSAGE_CONTROLPARAMETERRESPONSE_H
