// Generated by gencpp from file px4_command/GeneralInfoRequest.msg
// DO NOT EDIT!


#ifndef PX4_COMMAND_MESSAGE_GENERALINFOREQUEST_H
#define PX4_COMMAND_MESSAGE_GENERALINFOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_command
{
template <class ContainerAllocator>
struct GeneralInfoRequest_
{
  typedef GeneralInfoRequest_<ContainerAllocator> Type;

  GeneralInfoRequest_()
    : controllername()
    , TargetdroneID(0)
    , isMulti(false)  {
    }
  GeneralInfoRequest_(const ContainerAllocator& _alloc)
    : controllername(_alloc)
    , TargetdroneID(0)
    , isMulti(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _controllername_type;
  _controllername_type controllername;

   typedef int32_t _TargetdroneID_type;
  _TargetdroneID_type TargetdroneID;

   typedef uint8_t _isMulti_type;
  _isMulti_type isMulti;





  typedef boost::shared_ptr< ::px4_command::GeneralInfoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_command::GeneralInfoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GeneralInfoRequest_

typedef ::px4_command::GeneralInfoRequest_<std::allocator<void> > GeneralInfoRequest;

typedef boost::shared_ptr< ::px4_command::GeneralInfoRequest > GeneralInfoRequestPtr;
typedef boost::shared_ptr< ::px4_command::GeneralInfoRequest const> GeneralInfoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_command::GeneralInfoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_command::GeneralInfoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_command::GeneralInfoRequest_<ContainerAllocator1> & lhs, const ::px4_command::GeneralInfoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.controllername == rhs.controllername &&
    lhs.TargetdroneID == rhs.TargetdroneID &&
    lhs.isMulti == rhs.isMulti;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_command::GeneralInfoRequest_<ContainerAllocator1> & lhs, const ::px4_command::GeneralInfoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_command

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_command::GeneralInfoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_command::GeneralInfoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_command::GeneralInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_command::GeneralInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_command::GeneralInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_command::GeneralInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_command::GeneralInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97aa6d69d2fc2f46be1adb5689f7efe3";
  }

  static const char* value(const ::px4_command::GeneralInfoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97aa6d69d2fc2f46ULL;
  static const uint64_t static_value2 = 0xbe1adb5689f7efe3ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_command::GeneralInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_command/GeneralInfoRequest";
  }

  static const char* value(const ::px4_command::GeneralInfoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_command::GeneralInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string controllername\n"
"int32 TargetdroneID\n"
"bool isMulti\n"
;
  }

  static const char* value(const ::px4_command::GeneralInfoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_command::GeneralInfoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.controllername);
      stream.next(m.TargetdroneID);
      stream.next(m.isMulti);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GeneralInfoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_command::GeneralInfoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_command::GeneralInfoRequest_<ContainerAllocator>& v)
  {
    s << indent << "controllername: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.controllername);
    s << indent << "TargetdroneID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.TargetdroneID);
    s << indent << "isMulti: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isMulti);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_COMMAND_MESSAGE_GENERALINFOREQUEST_H
