// Generated by gencpp from file px4_command/SetHome.msg
// DO NOT EDIT!


#ifndef PX4_COMMAND_MESSAGE_SETHOME_H
#define PX4_COMMAND_MESSAGE_SETHOME_H

#include <ros/service_traits.h>


#include <px4_command/SetHomeRequest.h>
#include <px4_command/SetHomeResponse.h>


namespace px4_command
{

struct SetHome
{

typedef SetHomeRequest Request;
typedef SetHomeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetHome
} // namespace px4_command


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::px4_command::SetHome > {
  static const char* value()
  {
    return "798e15e3d217d7b631c2305a881a5677";
  }

  static const char* value(const ::px4_command::SetHome&) { return value(); }
};

template<>
struct DataType< ::px4_command::SetHome > {
  static const char* value()
  {
    return "px4_command/SetHome";
  }

  static const char* value(const ::px4_command::SetHome&) { return value(); }
};


// service_traits::MD5Sum< ::px4_command::SetHomeRequest> should match
// service_traits::MD5Sum< ::px4_command::SetHome >
template<>
struct MD5Sum< ::px4_command::SetHomeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::px4_command::SetHome >::value();
  }
  static const char* value(const ::px4_command::SetHomeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::px4_command::SetHomeRequest> should match
// service_traits::DataType< ::px4_command::SetHome >
template<>
struct DataType< ::px4_command::SetHomeRequest>
{
  static const char* value()
  {
    return DataType< ::px4_command::SetHome >::value();
  }
  static const char* value(const ::px4_command::SetHomeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::px4_command::SetHomeResponse> should match
// service_traits::MD5Sum< ::px4_command::SetHome >
template<>
struct MD5Sum< ::px4_command::SetHomeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::px4_command::SetHome >::value();
  }
  static const char* value(const ::px4_command::SetHomeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::px4_command::SetHomeResponse> should match
// service_traits::DataType< ::px4_command::SetHome >
template<>
struct DataType< ::px4_command::SetHomeResponse>
{
  static const char* value()
  {
    return DataType< ::px4_command::SetHome >::value();
  }
  static const char* value(const ::px4_command::SetHomeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PX4_COMMAND_MESSAGE_SETHOME_H
