// Generated by gencpp from file px4_command/SinglePayloadAction.msg
// DO NOT EDIT!


#ifndef PX4_COMMAND_MESSAGE_SINGLEPAYLOADACTION_H
#define PX4_COMMAND_MESSAGE_SINGLEPAYLOADACTION_H

#include <ros/service_traits.h>


#include <px4_command/SinglePayloadActionRequest.h>
#include <px4_command/SinglePayloadActionResponse.h>


namespace px4_command
{

struct SinglePayloadAction
{

typedef SinglePayloadActionRequest Request;
typedef SinglePayloadActionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SinglePayloadAction
} // namespace px4_command


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::px4_command::SinglePayloadAction > {
  static const char* value()
  {
    return "901dfe89bb4f4622133561aed17b3eb7";
  }

  static const char* value(const ::px4_command::SinglePayloadAction&) { return value(); }
};

template<>
struct DataType< ::px4_command::SinglePayloadAction > {
  static const char* value()
  {
    return "px4_command/SinglePayloadAction";
  }

  static const char* value(const ::px4_command::SinglePayloadAction&) { return value(); }
};


// service_traits::MD5Sum< ::px4_command::SinglePayloadActionRequest> should match
// service_traits::MD5Sum< ::px4_command::SinglePayloadAction >
template<>
struct MD5Sum< ::px4_command::SinglePayloadActionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::px4_command::SinglePayloadAction >::value();
  }
  static const char* value(const ::px4_command::SinglePayloadActionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::px4_command::SinglePayloadActionRequest> should match
// service_traits::DataType< ::px4_command::SinglePayloadAction >
template<>
struct DataType< ::px4_command::SinglePayloadActionRequest>
{
  static const char* value()
  {
    return DataType< ::px4_command::SinglePayloadAction >::value();
  }
  static const char* value(const ::px4_command::SinglePayloadActionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::px4_command::SinglePayloadActionResponse> should match
// service_traits::MD5Sum< ::px4_command::SinglePayloadAction >
template<>
struct MD5Sum< ::px4_command::SinglePayloadActionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::px4_command::SinglePayloadAction >::value();
  }
  static const char* value(const ::px4_command::SinglePayloadActionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::px4_command::SinglePayloadActionResponse> should match
// service_traits::DataType< ::px4_command::SinglePayloadAction >
template<>
struct DataType< ::px4_command::SinglePayloadActionResponse>
{
  static const char* value()
  {
    return DataType< ::px4_command::SinglePayloadAction >::value();
  }
  static const char* value(const ::px4_command::SinglePayloadActionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PX4_COMMAND_MESSAGE_SINGLEPAYLOADACTION_H
