# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from px4_command/AuxiliaryState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class AuxiliaryState(genpy.Message):
  _md5sum = "9bef9dbc2ce246f94ec35942903155d4"
  _type = "px4_command/AuxiliaryState"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

## quadrotor attitude

float32  q_0     ##
float32  q_1     ##
float32  q_2     ##
float32  q_3     ##

float32  r_jx    ## [m]
float32  r_jy    ## [m]

float32  v_jx    ## [m]
float32  v_jy    ## [m]

float32  L_measured ## [m] measured L from mocap system

## payload pos error

float32  pos_error_x ## [m]
float32  pos_error_y ## [m]
float32  pos_error_z ## [m]

float32  angle_error_x  ## 
float32  angle_error_y  ## 
float32  angle_error_z  ## 

## quadrotor euler angle

float32  Euler_roll     ##
float32  Euler_pitch    ##
float32  Euler_yaw      ##

float32  fLj_x  ## [N]
float32  fLj_y  ## [N]
float32  fLj_z  ## [N]

float32  Delta_jp_x ## [N]
float32  Delta_jp_y ## [N]
float32  Delta_jp_z ## [N]

float32  acc_x  ##
float32  acc_y  ##
float32  acc_z  ##

float32  rd_jx  ## 
float32  rd_jy  ##
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','q_0','q_1','q_2','q_3','r_jx','r_jy','v_jx','v_jy','L_measured','pos_error_x','pos_error_y','pos_error_z','angle_error_x','angle_error_y','angle_error_z','Euler_roll','Euler_pitch','Euler_yaw','fLj_x','fLj_y','fLj_z','Delta_jp_x','Delta_jp_y','Delta_jp_z','acc_x','acc_y','acc_z','rd_jx','rd_jy']
  _slot_types = ['std_msgs/Header','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,q_0,q_1,q_2,q_3,r_jx,r_jy,v_jx,v_jy,L_measured,pos_error_x,pos_error_y,pos_error_z,angle_error_x,angle_error_y,angle_error_z,Euler_roll,Euler_pitch,Euler_yaw,fLj_x,fLj_y,fLj_z,Delta_jp_x,Delta_jp_y,Delta_jp_z,acc_x,acc_y,acc_z,rd_jx,rd_jy

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AuxiliaryState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.q_0 is None:
        self.q_0 = 0.
      if self.q_1 is None:
        self.q_1 = 0.
      if self.q_2 is None:
        self.q_2 = 0.
      if self.q_3 is None:
        self.q_3 = 0.
      if self.r_jx is None:
        self.r_jx = 0.
      if self.r_jy is None:
        self.r_jy = 0.
      if self.v_jx is None:
        self.v_jx = 0.
      if self.v_jy is None:
        self.v_jy = 0.
      if self.L_measured is None:
        self.L_measured = 0.
      if self.pos_error_x is None:
        self.pos_error_x = 0.
      if self.pos_error_y is None:
        self.pos_error_y = 0.
      if self.pos_error_z is None:
        self.pos_error_z = 0.
      if self.angle_error_x is None:
        self.angle_error_x = 0.
      if self.angle_error_y is None:
        self.angle_error_y = 0.
      if self.angle_error_z is None:
        self.angle_error_z = 0.
      if self.Euler_roll is None:
        self.Euler_roll = 0.
      if self.Euler_pitch is None:
        self.Euler_pitch = 0.
      if self.Euler_yaw is None:
        self.Euler_yaw = 0.
      if self.fLj_x is None:
        self.fLj_x = 0.
      if self.fLj_y is None:
        self.fLj_y = 0.
      if self.fLj_z is None:
        self.fLj_z = 0.
      if self.Delta_jp_x is None:
        self.Delta_jp_x = 0.
      if self.Delta_jp_y is None:
        self.Delta_jp_y = 0.
      if self.Delta_jp_z is None:
        self.Delta_jp_z = 0.
      if self.acc_x is None:
        self.acc_x = 0.
      if self.acc_y is None:
        self.acc_y = 0.
      if self.acc_z is None:
        self.acc_z = 0.
      if self.rd_jx is None:
        self.rd_jx = 0.
      if self.rd_jy is None:
        self.rd_jy = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.q_0 = 0.
      self.q_1 = 0.
      self.q_2 = 0.
      self.q_3 = 0.
      self.r_jx = 0.
      self.r_jy = 0.
      self.v_jx = 0.
      self.v_jy = 0.
      self.L_measured = 0.
      self.pos_error_x = 0.
      self.pos_error_y = 0.
      self.pos_error_z = 0.
      self.angle_error_x = 0.
      self.angle_error_y = 0.
      self.angle_error_z = 0.
      self.Euler_roll = 0.
      self.Euler_pitch = 0.
      self.Euler_yaw = 0.
      self.fLj_x = 0.
      self.fLj_y = 0.
      self.fLj_z = 0.
      self.Delta_jp_x = 0.
      self.Delta_jp_y = 0.
      self.Delta_jp_z = 0.
      self.acc_x = 0.
      self.acc_y = 0.
      self.acc_z = 0.
      self.rd_jx = 0.
      self.rd_jy = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_29f().pack(_x.q_0, _x.q_1, _x.q_2, _x.q_3, _x.r_jx, _x.r_jy, _x.v_jx, _x.v_jy, _x.L_measured, _x.pos_error_x, _x.pos_error_y, _x.pos_error_z, _x.angle_error_x, _x.angle_error_y, _x.angle_error_z, _x.Euler_roll, _x.Euler_pitch, _x.Euler_yaw, _x.fLj_x, _x.fLj_y, _x.fLj_z, _x.Delta_jp_x, _x.Delta_jp_y, _x.Delta_jp_z, _x.acc_x, _x.acc_y, _x.acc_z, _x.rd_jx, _x.rd_jy))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 116
      (_x.q_0, _x.q_1, _x.q_2, _x.q_3, _x.r_jx, _x.r_jy, _x.v_jx, _x.v_jy, _x.L_measured, _x.pos_error_x, _x.pos_error_y, _x.pos_error_z, _x.angle_error_x, _x.angle_error_y, _x.angle_error_z, _x.Euler_roll, _x.Euler_pitch, _x.Euler_yaw, _x.fLj_x, _x.fLj_y, _x.fLj_z, _x.Delta_jp_x, _x.Delta_jp_y, _x.Delta_jp_z, _x.acc_x, _x.acc_y, _x.acc_z, _x.rd_jx, _x.rd_jy,) = _get_struct_29f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_29f().pack(_x.q_0, _x.q_1, _x.q_2, _x.q_3, _x.r_jx, _x.r_jy, _x.v_jx, _x.v_jy, _x.L_measured, _x.pos_error_x, _x.pos_error_y, _x.pos_error_z, _x.angle_error_x, _x.angle_error_y, _x.angle_error_z, _x.Euler_roll, _x.Euler_pitch, _x.Euler_yaw, _x.fLj_x, _x.fLj_y, _x.fLj_z, _x.Delta_jp_x, _x.Delta_jp_y, _x.Delta_jp_z, _x.acc_x, _x.acc_y, _x.acc_z, _x.rd_jx, _x.rd_jy))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 116
      (_x.q_0, _x.q_1, _x.q_2, _x.q_3, _x.r_jx, _x.r_jy, _x.v_jx, _x.v_jy, _x.L_measured, _x.pos_error_x, _x.pos_error_y, _x.pos_error_z, _x.angle_error_x, _x.angle_error_y, _x.angle_error_z, _x.Euler_roll, _x.Euler_pitch, _x.Euler_yaw, _x.fLj_x, _x.fLj_y, _x.fLj_z, _x.Delta_jp_x, _x.Delta_jp_y, _x.Delta_jp_z, _x.acc_x, _x.acc_y, _x.acc_z, _x.rd_jx, _x.rd_jy,) = _get_struct_29f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_29f = None
def _get_struct_29f():
    global _struct_29f
    if _struct_29f is None:
        _struct_29f = struct.Struct("<29f")
    return _struct_29f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
