# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from px4_command/FleetStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class FleetStatus(genpy.Message):
  _md5sum = "342d52e91e004889154425a4215db94b"
  _type = "px4_command/FleetStatus"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

## fleet info for robust payload control
float32  r_jx         ## [m]
float32  r_jy         ## [m]
float32  v_jx         ## [m/s]
float32  v_jy         ## [m/s]
float32  f_Ljx        ## [N]
float32  f_Ljy        ## [N]
float32  f_Ljz        ## [N]
float32  delta_jx     ## [N]
float32  delta_jy     ## [N]
float32  delta_jz     ## [N]
float32  rd_jx        ## [m]
float32  rd_jy        ## [m]
bool emergency        ##
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','r_jx','r_jy','v_jx','v_jy','f_Ljx','f_Ljy','f_Ljz','delta_jx','delta_jy','delta_jz','rd_jx','rd_jy','emergency']
  _slot_types = ['std_msgs/Header','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,r_jx,r_jy,v_jx,v_jy,f_Ljx,f_Ljy,f_Ljz,delta_jx,delta_jy,delta_jz,rd_jx,rd_jy,emergency

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FleetStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.r_jx is None:
        self.r_jx = 0.
      if self.r_jy is None:
        self.r_jy = 0.
      if self.v_jx is None:
        self.v_jx = 0.
      if self.v_jy is None:
        self.v_jy = 0.
      if self.f_Ljx is None:
        self.f_Ljx = 0.
      if self.f_Ljy is None:
        self.f_Ljy = 0.
      if self.f_Ljz is None:
        self.f_Ljz = 0.
      if self.delta_jx is None:
        self.delta_jx = 0.
      if self.delta_jy is None:
        self.delta_jy = 0.
      if self.delta_jz is None:
        self.delta_jz = 0.
      if self.rd_jx is None:
        self.rd_jx = 0.
      if self.rd_jy is None:
        self.rd_jy = 0.
      if self.emergency is None:
        self.emergency = False
    else:
      self.header = std_msgs.msg.Header()
      self.r_jx = 0.
      self.r_jy = 0.
      self.v_jx = 0.
      self.v_jy = 0.
      self.f_Ljx = 0.
      self.f_Ljy = 0.
      self.f_Ljz = 0.
      self.delta_jx = 0.
      self.delta_jy = 0.
      self.delta_jz = 0.
      self.rd_jx = 0.
      self.rd_jy = 0.
      self.emergency = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_12fB().pack(_x.r_jx, _x.r_jy, _x.v_jx, _x.v_jy, _x.f_Ljx, _x.f_Ljy, _x.f_Ljz, _x.delta_jx, _x.delta_jy, _x.delta_jz, _x.rd_jx, _x.rd_jy, _x.emergency))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 49
      (_x.r_jx, _x.r_jy, _x.v_jx, _x.v_jy, _x.f_Ljx, _x.f_Ljy, _x.f_Ljz, _x.delta_jx, _x.delta_jy, _x.delta_jz, _x.rd_jx, _x.rd_jy, _x.emergency,) = _get_struct_12fB().unpack(str[start:end])
      self.emergency = bool(self.emergency)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_12fB().pack(_x.r_jx, _x.r_jy, _x.v_jx, _x.v_jy, _x.f_Ljx, _x.f_Ljy, _x.f_Ljz, _x.delta_jx, _x.delta_jy, _x.delta_jz, _x.rd_jx, _x.rd_jy, _x.emergency))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 49
      (_x.r_jx, _x.r_jy, _x.v_jx, _x.v_jy, _x.f_Ljx, _x.f_Ljy, _x.f_Ljz, _x.delta_jx, _x.delta_jy, _x.delta_jz, _x.rd_jx, _x.rd_jy, _x.emergency,) = _get_struct_12fB().unpack(str[start:end])
      self.emergency = bool(self.emergency)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12fB = None
def _get_struct_12fB():
    global _struct_12fB
    if _struct_12fB is None:
        _struct_12fB = struct.Struct("<12fB")
    return _struct_12fB
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
